<?php

/**
 * PluginChuckPassword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginChuckPassword extends BaseChuckPassword
{

    public function generatePass()
    {
        $password = substr(sha1(uniqid()), 0, 20);
        $this->setPass($password);
    }

    public function preSave($event)
    {
        $this->setCreatedAt(date("Y-m-d H:i:s"));
        parent::preSave($event);
    }
}