<?php

/**
 * PluginMenuPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMenuPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMenuPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMenuPermission');
    }
}