<?php

/**
 * PluginChuckPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginChuckPasswordTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object PluginChuckPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginChuckPassword');
    }

    public function findCurrent()
    {
        $query = $this->createQuery("cp")
                ->where("created_at < ?", date("Y-m-d H:i:s"))
                ->andWhere("created_at > ?", date("Y-m-d H:i:s", strtotime('-5min')));
        return $query->fetchOne();
    }
}