generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Article
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partial
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        search:
          label: Rechercher
        title:
          label: Titre
        contents:
          label: Contenu
        slug:
          label: Clé
      list:
        title: Blocs statiques
        display: [title, slug]
        table_method: findPartials
        sort: [title, asc]
        actions: []
        object_actions:
          _edit: ~
          _show: ~
        batch_actions: []
      show:
        title: %%title%%
        display: [title, slug, contents]
        actions:
          _edit: ~
          _list: ~
      filter:
        display: [search]
      form:
        class: PartialForm
        template: columns
        display: [title, contents]
        columns: [slug]
      edit:
        title: Edition de "%%title%%"
        actions:
          _list: ~
          _save: ~
          _show: ~
