all:
  sf_guard_plugin:
    success_signout_url: '@homepage'
  sf_admin_template:
    menus:
      articles:
        label: Articles
        route_prefix: article
        credentials: [Article]
      partials:
        label: Blocs statiques
        route_prefix: partial
        credentials: [Partial]
      menus:
        label: Arborescence
        route_prefix: menu
        credentials: [Menu]
      users:
        label: Utilisateurs
        route_prefix: sf_guard_user
        credentials: [User]
      groups:
        label: Groupes
        route_prefix: sf_guard_group
        credentials: [Group]
      permissions:
        label: Permissions
        route_prefix: sf_guard_permission
        credentials: [Permission]