rss:
  url:   /flux.rss
  param: { module: sfCms, action: rss, sf_format: xml }

sitemap:
  url:   /sitemap.xml
  param: { module: sfCms, action: sitemap, sf_format: xml }

search:
  url:   /rechercher
  param: { module: sfCms, action: search }

menu:
  class: sfDoctrineRouteCollection
  options:
    model:                Menu
    module:               menu
    prefix_path:          /admin/arborescence
    column:               id
    with_wildcard_routes: true
    object_actions:
      add:                [get, post]

article:
  class: sfDoctrineRouteCollection
  options:
    model:                Article
    module:               article
    prefix_path:          /admin/articles
    column:               id
    with_wildcard_routes: true
    object_actions:
      publish:            [get, post]
      unpublish:          [get, post]
    collection_actions:
      tags_autocomplete:  [post]

partial:
  class: sfDoctrineRouteCollection
  options:
    model:                Article
    module:               partial
    prefix_path:          /admin/blocs
    column:               id
    with_wildcard_routes: true